[build-system]
requires = ["setuptools>=65", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "robotframework-okw-web-selenium"
version = "0.4.1"
description = "Selenium driver for OKW4Robot - Web GUI test automation with Chrome, Firefox and more."
readme = "README.md"
requires-python = ">=3.10"
keywords = ["robotframework", "testing", "testautomation", "gui", "selenium", "okw", "web"]
dependencies = [
  "robotframework-okw4robot>=0.5.1",
  "robotframework-seleniumlibrary>=6.0",
  "selenium>=4.0",
]
authors = [
  { name = "Zoltán Hrabovszki" }
]
license = { file = "LICENSE" }
classifiers = [
  "Development Status :: 4 - Beta",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Framework :: Robot Framework",
  "Framework :: Robot Framework :: Library",
  "Topic :: Software Development :: Testing",
]

[project.urls]
Repository = "https://github.com/Hrabovszki1023/robotframework-okw-web-selenium"
Homepage = "https://github.com/Hrabovszki1023/robotframework-okw-web-selenium"
Documentation = "https://hrabovszki1023.github.io/robotframework-okw-web-selenium/"

[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false

[tool.setuptools.package-data]
okw_web_selenium = ["locators/*.yaml"]

[project.optional-dependencies]
dev = ["pytest>=7.0"]

[tool.pytest.ini_options]
testpaths = ["tests"]
