from abc import ABC, abstractmethod

class UiAdapter(ABC):
    @abstractmethod
    def click(self, locator): ...
    @abstractmethod
    def double_click(self, locator): ...
    @abstractmethod
    def set_value(self, locator, value): ...
    @abstractmethod
    def type_key(self, locator, value): ...
    @abstractmethod
    def get_value(self, locator): ...
